version: '3.8'

services:
  hana-ai-api:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    image: hana-ai-toolkit:latest
    container_name: hana-ai-toolkit
    env_file:
      - btp-environment.env
    ports:
      - "${API_PORT:-8000}:8000"
    volumes:
      - ../:/app
    restart: unless-stopped
    networks:
      - hana-ai-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"
    restart: unless-stopped
    networks:
      - hana-ai-network
    # Only accessible within the network, not exposed externally

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    networks:
      - hana-ai-network
    # Only accessible within the network, not exposed externally

networks:
  hana-ai-network:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data: