name: Release

on:
  push:
    tags:
      - v*

jobs:
  build:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    environment: pypi
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Install essential build tools
      - name: Install build dependencies
        run: pip install -U setuptools wheel build pkginfo twine

      # Optional: Only include if you need dependencies for building
      #- name: Install project dependencies
      #  run: pip install -r requirements.txt

      # New step to clean previous builds
      - name: Clean dist directory
        run: rm -rf dist/ build/ hana_ai.egg-info/

      # Build using setup.py directly
      - name: Build release distribution
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
