name: Release

on:
  push:
    tags:
      - v*

jobs:
  build:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    environment: pypi
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Install essential build tools
      - name: Install build dependencies
        run: pip install setuptools wheel

      # Optional: Only include if you need dependencies for building
      - name: Install project dependencies
        run: pip install -r requirements.txt

      # Build using setup.py directly
      - name: Build release distribution
        run: python setup.py sdist bdist_wheel

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.14