name: Release

on:
  push:
    tags:
      - v*

jobs:
  build:
    permissions:
      contents: read
      # id-token: write is required to release using the trusted publisher
      id-token: write
    runs-on: ubuntu-latest
    # The GitHub Actions Environment configured for the trusted publisher
    environment: <pypi:packageName>
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Process to build/test your package
      # Adjust as necessary for your project
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Build release distribution
        run: python -m build .

      # This step releases your built version to PyPI
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.14
